name: Updater (WIP)

on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: HugoBlox/gh-action-updater@v1
        with:
          feed-url: https://hugoblox.com/rss.xml
          readme-section: news
